# 实际开发的时候，database配置务必修改一下

development:
  adapter: mysql
  encoding: utf8
  database: upload_video_development
  username: root
  password: root
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: upload_video
  username: root
  password: root
  host: localhost
